// Regenerates fixtures/vwc-trust-tasks-path.json by calling the REAL shipped
// witness-server builder — not a reimplementation of it.
//
//   buildWitnessCredentialJson()          witness-server/src/WitnessService.ts:231
//   + the four binding lines               witness-server/src/trustTasks/WitnessTaskSessions.ts:258-262
//
// The captured legacy VWC (ref-07's edge-witnessed-captured.json) comes from the
// vrc-reference demo path, which predates Trust Task Context Binding and carries
// no taskContext. This produces the shape the production trust-tasks path emits.
import { writeFileSync } from 'node:fs'

const ws = await import('../../bifold/packages/witness-server/dist/WitnessService.js')
const tt = await import('../../bifold/packages/trust-tasks/dist/index.js').catch(() => null)

const { buildWitnessCredentialJson } = ws.default ?? ws

// The observed VRC: the real captured Alice→Bob half from ref-07's fixture.
const captured = JSON.parse(
  (await import('node:fs')).readFileSync('../ref-07-dtg-edge-semantics/fixtures/edge-witnessed-captured.json', 'utf8')
)
const observedVrc = captured.vrcs[0].credential
const presentation = { verifiableCredential: [observedVrc] }

const SESSION_ID = 'urn:uuid:5e5510f0-0000-4000-8000-000000000001'
const vwc = buildWitnessCredentialJson(presentation, {
  issuerDid: 'did:peer:0z6Mkn1HiMU6BqSPJSR9ydCmDUuNc68foyR7A7V4RugmGy27K',
  witnessName: 'Keyring Witness',
  sessionId: SESSION_ID,
  verificationMethod: 'did:peer:0z6Mkn1HiMU6BqSPJSR9ydCmDUuNc68foyR7A7V4RugmGy27K#key-1',
  eventName: 'ref-07b fixture',
})

// WitnessTaskSessions.ts:258-262 — verbatim
const subject = vwc.credentialSubject ?? {}
subject.parties = [captured.vrcs[0].credential.issuer, captured.vrcs[1].credential.issuer]
subject.taskContext = SESSION_ID
subject.taskDigestMultibase = 'zQmTaskDigestPlaceholderForFixtureOnly000000000'
vwc.credentialSubject = subject

writeFileSync(
  'fixtures/vwc-trust-tasks-path.json',
  JSON.stringify(
    {
      _provenance:
        'Generated by build-fixture.mjs calling witness-server dist buildWitnessCredentialJson() plus the four binding lines from WitnessTaskSessions.ts:258-262. Unsigned: this rung tests shape and member coverage, not proofs.',
      credential: vwc,
    },
    null,
    2
  ) + '\n'
)
console.log('wrote fixtures/vwc-trust-tasks-path.json')
